# Calcul Matriciel
## On python

This notebook recalls some basic data structures and functions of Python.

## Getting started

In [1]:
import numpy as np

## Data structures

In [2]:
# A number
a = 3

In [3]:
# A list
b = [3, 5, 2, 5]
b[1]

5

In [4]:
# A set
set(b)

{2, 3, 5}

In [5]:
# A strange list
c = [2, "toto", 3.14]

In [6]:
# A dictionary
d = {0: "toto", 1: "tata", 3: "tutu"}
d[3]

'tutu'

In [7]:
# A strange dictionary
e = {0: "toto", "a": 32, 3.2: [2,3]}
e[3.2]


[2, 3]

In [8]:
# A dictionary of dictionaries
f = {0: {1: "toto", 2: "tata"}, 1: {}, 3: {0: "tutu", 1: "titi"}}
f[0][2]

'tata'

In [9]:
f[0][1] = 'test' # update existing entry
print(f)

{0: {1: 'test', 2: 'tata'}, 1: {}, 3: {0: 'tutu', 1: 'titi'}}


In [10]:
f['New_field'] = "New_value" # Add new entry
print(f)

{0: {1: 'test', 2: 'tata'}, 1: {}, 3: {0: 'tutu', 1: 'titi'}, 'New_field': 'New_value'}


## Loops and tests

In [12]:
print("*** \n  *if test*")

if 2+2==4:
    print("2+2=4")
else:
    print("something's very wrong here")
    
print("*** \n  *for loop*")
    
for i in range(10):
    print("for: ",i)

    
print("*** \n  *while loop*")

i=0
while i<=10:
    print("while: ",i)
    i=i+1
        


*** 
  *if test*
2+2=4
*** 
  *for loop*
for:  0
for:  1
for:  2
for:  3
for:  4
for:  5
for:  6
for:  7
for:  8
for:  9
*** 
  *while loop*
while:  0
while:  1
while:  2
while:  3
while:  4
while:  5
while:  6
while:  7
while:  8
while:  9
while:  10


## List comprehensions

In [12]:
[i**2 for i in range(4)]

[0, 1, 4, 9]

In [13]:
{i:i**2 for i in range(4)}

{0: 0, 1: 1, 2: 4, 3: 9}

In [14]:
g = [[2], [2,4,5], [9,0]]
[len(a) for a in g]

[1, 3, 2]

## Sorting

In [15]:
g = [[2], [2,4,5], [9,0]]
sorted(g, key = len, reverse = True)

[[2, 4, 5], [9, 0], [2]]

In [16]:
h = [3, 5, 2, 5, 8]
np.argsort(h)

array([2, 0, 1, 3, 4])

## Random sampling

In [17]:
h = [3, 5, 2, 5, 8]
np.random.choice(h)

5

In [18]:
np.random.shuffle(h)
h

[2, 8, 5, 3, 5]

## Linear algebra

In [19]:
u = np.array([1,2])
print(u)

[1 2]


In [20]:
print(np.ones(2))
np.dot(u,np.ones(2))

[1. 1.]


3.0

In [21]:
A = np.array([[1,1],[0,1]])

In [22]:
#Usual matrix/vector multiplication
np.dot(A,u)

array([3, 2])

In [23]:
#Notice the difference with the (pointwise) multiplication
A * u

array([[1, 2],
       [0, 2]])